#!/bin/bash
#comments
if [[ $1 = *.urls ]]; then
    wget -i $1 --trust-server-names=on --restrict-file-names=nocontrol -c
else
    wget $1 --trust-server-names=on --restrict-file-names=nocontrol -c
fi
